/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.53
 * Generated at: 2022-07-08 12:19:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class post_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>여행가기 좋은날</title>\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("   <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("   <link href=\"https://fonts.googleapis.com/css2?family=Gugi&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"fontawesome/css/all.min.css\"> <!-- https://fontawesome.com/ -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/magnific-popup.css\"> \r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/templatemo-ocean-vibes.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/animate.css\">\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("     <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("       * {font-family: 'Gugi', cursive }\r\n");
      out.write("        ul,ol.li {list-style: none; margin: 0; padding: 0;}\r\n");
      out.write("        nav {width: 1000px; height: 50px; margin:0 auto;}\r\n");
      out.write("        nav > ul {display:inline;}\r\n");
      out.write("       nav > ul > li > a {float: right; color: #212121; font-size: 20px;\r\n");
      out.write("            text-decoration: none; margin: 0px 30px 0 30px;\r\n");
      out.write("            font-weight: bold;}\r\n");
      out.write("            \r\n");
      out.write("        .gd-container {\r\n");
      out.write("  max-width: 1100px;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  margin: 0 auto;\r\n");
      out.write("  padding-left: 15px;\r\n");
      out.write("  padding-right: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#gtco-header { height: 700px; background-image: 700px; \r\n");
      out.write("background-repeat: no-repeat;\r\n");
      out.write("background-size: cover;}\r\n");
      out.write("\r\n");
      out.write(".top-left {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 8px;\r\n");
      out.write("  left: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("        #slider {width: 1000px; height: 700px; margin: 0 auto;}\r\n");
      out.write("        #slider > img {margin-left: 250px;}\r\n");
      out.write("        .tm-mt-0 {float: left; font-size: 50px;}\r\n");
      out.write("        #menubar {width: 1000px; margin: 0 auto;}\r\n");
      out.write("        footer {width:1000px; height:50px; margin:0 auto;}\r\n");
      out.write("        \r\n");
      out.write("    </style> \r\n");
      out.write("</head>\r\n");
      out.write("   <body>\r\n");
      out.write("       <header class=\"tm-site-header\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <nav>\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"destination.jsp\">여행지 추천</a></li>\r\n");
      out.write("                  <li><a href=\"course.jsp\">코스 추천</a></li>\r\n");
      out.write("                  <li><a href=\"festival.jsp\">축제</a></li>\r\n");
      out.write("                  <li><a href=\"login.jsp\">로그인</a></li>\r\n");
      out.write("                    <li><a href=\"mypage.jsp\" class=\"tm-mt-0 tm-mb-15\"><span class=\"tm-color-primary\">여행가기 좋은날</span></a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("   <div class=\"gtco-section\">\r\n");
      out.write("      <div class=\"gd-container\">\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-8 col-md-offset-2 text-center gtco-heading\">\r\n");
      out.write("               <h2>포스트</h2>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type=\"button\" value=\"글쓰기\" onclick=\"location.href='postInsert.jsp'\"></input>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"row\">\r\n");
      out.write("   <br><br><br>\r\n");
      out.write("            <div class=\"col-lg-4 col-md-4 col-sm-6\">\r\n");
      out.write("               <a href=\"images/img_1.jpg\" class=\"fh5co-card-item image-popup\">\r\n");
      out.write("                  <figure>\r\n");
      out.write("                     <div class=\"overlay\"><i class=\"ti-plus\"></i></div>\r\n");
      out.write("                     <img src=\"images/img_1.jpg\" alt=\"Image\" class=\"img-responsive\">\r\n");
      out.write("                  </figure>\r\n");
      out.write("                  <div class=\"fh5co-text\">\r\n");
      out.write("                     <h2>충청도</h2>\r\n");
      out.write("                     <p>역사와 자연이 조화로운 서산 여행</p>\r\n");
      out.write("                     <p><span class=\"btn btn-primary\"> 보러가기</span></p>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4 col-md-4 col-sm-6\">\r\n");
      out.write("               <a href=\"images/img_2.jpg\" class=\"fh5co-card-item image-popup\">\r\n");
      out.write("                  <figure>\r\n");
      out.write("                     <div class=\"overlay\"><i class=\"ti-plus\"></i></div>\r\n");
      out.write("                     <img src=\"images/img_2.jpg\" alt=\"Image\" class=\"img-responsive\">\r\n");
      out.write("                  </figure>\r\n");
      out.write("                  <div class=\"fh5co-text\">\r\n");
      out.write("                     <h2>강원도 </h2>\r\n");
      out.write("                     <p>영월로 떠나는 어느 여름날의 강원도 힐링여행</p>\r\n");
      out.write("                     <p><span class=\"btn btn-primary\">보러가기</span></p>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-4 col-md-4 col-sm-6\">\r\n");
      out.write("               <a href=\"images/img_3.jpg\" class=\"fh5co-card-item image-popup\">\r\n");
      out.write("                  <figure>\r\n");
      out.write("                     <div class=\"overlay\"><i class=\"ti-plus\"></i></div>\r\n");
      out.write("                     <img src=\"images/img_3.jpg\" alt=\"Image\" class=\"img-responsive\">\r\n");
      out.write("                  </figure>\r\n");
      out.write("                  <div class=\"fh5co-text\">\r\n");
      out.write("                     <h2>경상도</h2>\r\n");
      out.write("                     <p>반려견과의 특별한 하루를\r\n");
      out.write("                        경북 의성, 의성펫월드</p>\r\n");
      out.write("                     <p><span class=\"btn btn-primary\">보러가기</span></p>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-lg-4 col-md-4 col-sm-6\">\r\n");
      out.write("               <a href=\"images/img_4.jpg\" class=\"fh5co-card-item image-popup\">\r\n");
      out.write("                  <figure>\r\n");
      out.write("                     <div class=\"overlay\"><i class=\"ti-plus\"></i></div>\r\n");
      out.write("                     <img src=\"images/img_4.jpg\" alt=\"Image\" class=\"img-responsive\">\r\n");
      out.write("                  </figure>\r\n");
      out.write("                  <div class=\"fh5co-text\">\r\n");
      out.write("                     <h2>경기도</h2>\r\n");
      out.write("                     <p>하루만에 즐기는\r\n");
      out.write("                        수원 당일치기 여행코스</p>\r\n");
      out.write("                     <p><span class=\"btn btn-primary\">보러가기</span></p>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-lg-4 col-md-4 col-sm-6\">\r\n");
      out.write("               <a href=\"images/img_5.jpg\" class=\"fh5co-card-item image-popup\">\r\n");
      out.write("                  <figure>\r\n");
      out.write("                     <div class=\"overlay\"><i class=\"ti-plus\"></i></div>\r\n");
      out.write("                     <img src=\"images/img_5.jpg\" alt=\"Image\" class=\"img-responsive\">\r\n");
      out.write("                  </figure>\r\n");
      out.write("                  <div class=\"fh5co-text\">\r\n");
      out.write("                     <h2>전라도</h2>\r\n");
      out.write("                     <p>잠들지 않는 낭만의 도시, 여수를 만끽하다 </p>\r\n");
      out.write("                     <p><span class=\"btn btn-primary\">보러가기</span></p>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-lg-4 col-md-4 col-sm-6\">\r\n");
      out.write("               <a href=\"images/img_6.jpg\" class=\"fh5co-card-item image-popup\">\r\n");
      out.write("                  <figure>\r\n");
      out.write("                     <div class=\"overlay\"><i class=\"ti-plus\"></i></div>\r\n");
      out.write("                     <img src=\"images/img_6.jpg\" alt=\"Image\" class=\"img-responsive\">\r\n");
      out.write("                  </figure>\r\n");
      out.write("                  <div class=\"fh5co-text\">\r\n");
      out.write("                     <h2>제주도</h2>\r\n");
      out.write("                     <p>섬 안에 섬을 여행하는 방법, 가파도 여행 코스</p>\r\n");
      out.write("                     <p><span class=\"btn btn-primary\">보러가기</span></p>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <br><br><br>\r\n");
      out.write("\r\n");
      out.write("   <footer id=\"gtco-footer\" role=\"contentinfo\">\r\n");
      out.write("      <div class=\"gtco-container\">\r\n");
      out.write("         <div class=\"row row-p   b-md\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-4\">\r\n");
      out.write("               <div class=\"gtco-widget\">\r\n");
      out.write("                  <h3>About Us</h3>\r\n");
      out.write("                  <p> 2022 GoodDayTrip Team</p>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-2 col-md-push-1\">\r\n");
      out.write("               <div class=\"gtco-widget\">\r\n");
      out.write("                  <h3>Destination</h3>\r\n");
      out.write("                  <ul class=\"gtco-footer-links\">\r\n");
      out.write("                     <li><a href=\"#\">서울</a></li>\r\n");
      out.write("                        <li><a href=\"#\">경기도</a></li>\r\n");
      out.write("                        <li><a href=\"#\">강원도</a></li>\r\n");
      out.write("                        <li><a href=\"#\">충청도</a></li>\r\n");
      out.write("                        <li><a href=\"#\">전라도</a></li>\r\n");
      out.write("                        <li><a href=\"#\">경상도</a></li>\r\n");
      out.write("                        <li><a href=\"#\">제주도</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-2 col-md-push-1\">\r\n");
      out.write("               <div class=\"gtco-widget\">\r\n");
      out.write("                  <h3>POST   </h3>\r\n");
      out.write("                  <ul class=\"gtco-footer-links\">\r\n");
      out.write("                     <li><a href=\"#\">여행지 포스트</a></li>\r\n");
      out.write("                     <li><a href=\"#\">코스 포스트</a></li>\r\n");
      out.write("                     <li><a href=\"#\">축제 포스트</a></li>\r\n");
      out.write("                     \r\n");
      out.write("                  </ul>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-md-3 col-md-push-1\">\r\n");
      out.write("               <div class=\"gtco-widget\">\r\n");
      out.write("                  <h3>Contact us</h3>\r\n");
      out.write("                  <ul class=\"gtco-quick-contact\">\r\n");
      out.write("                     <li><a href=\"#\"><i class=\"icon-phone\"></i> +82 010-000-0000</a></li>\r\n");
      out.write("                     <li><a href=\"#\"><i class=\"icon-mail2\"></i> gooddaytrip@goodday.co</a></li>\r\n");
      out.write("                     <li><a href=\"#\"><i class=\"icon-chat\"></i> Live Chat</a></li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("         <div class=\"row copyright\">\r\n");
      out.write("            <div class=\"col-md-12\">\r\n");
      out.write("               <p class=\"pull-left\">\r\n");
      out.write("                  <small class=\"block\">&copy; 2022 GoodDayTrip Team</small> \r\n");
      out.write("         \r\n");
      out.write("               </p>\r\n");
      out.write("               <p class=\"pull-right\">\r\n");
      out.write("                  <ul class=\"gtco-social-icons pull-right\">\r\n");
      out.write("                     <li><a href=\"#\"><i class=\"icon-twitter\"></i></a></li>\r\n");
      out.write("                     <li><a href=\"#\"><i class=\"icon-facebook\"></i></a></li>\r\n");
      out.write("                     <li><a href=\"#\"><i class=\"icon-instagram\"></i></a></li>\r\n");
      out.write("               \r\n");
      out.write("                  </ul>\r\n");
      out.write("               </p>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("   </footer>\r\n");
      out.write("   <!-- </div> -->\r\n");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("   <div class=\"gototop js-top\">\r\n");
      out.write("      <a href=\"#\" class=\"js-gotop\"><i class=\"icon-arrow-up\"></i></a>\r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   <!-- jQuery -->\r\n");
      out.write("   <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("   <!-- jQuery Easing -->\r\n");
      out.write("   <script src=\"js/jquery.easing.1.3.js\"></script>\r\n");
      out.write("   <!-- Bootstrap -->\r\n");
      out.write("   <script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("   <!-- Waypoints -->\r\n");
      out.write("   <script src=\"js/jquery.waypoints.min.js\"></script>\r\n");
      out.write("   <!-- Carousel -->\r\n");
      out.write("   <script src=\"js/owl.carousel.min.js\"></script>\r\n");
      out.write("   <!-- countTo -->\r\n");
      out.write("   <script src=\"js/jquery.countTo.js\"></script>\r\n");
      out.write("\r\n");
      out.write("   <!-- Stellar Parallax -->\r\n");
      out.write("   <script src=\"js/jquery.stellar.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("   <!-- Magnific Popup -->\r\n");
      out.write("   <script src=\"js/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("   <script src=\"js/magnific-popup-options.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("   <!-- Datepicker -->\r\n");
      out.write("   <script src=\"js/bootstrap-datepicker.min.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   <!-- Main -->\r\n");
      out.write("   <script src=\"js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("   </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
